### ISSUE TITLE
Error from DittoCopier.py when running com.github.dataJAR-recipes.pkg.VMware Fusion 11

### ISSUE THREAD

**Issue by rtrouton** [autopkg/dataJAR-recipes#104]
I'm testing the latest rev of the VMware Fusion 11 .pkg recipe and I'm seeing the following error (appears to be from `DittoCopier.py`):

```
username@computername VMWareFusion % autopkg run "com.github.dataJAR-recipes.pkg.VMware Fusion 11" -vvvvv
Processing com.github.dataJAR-recipes.pkg.VMware Fusion 11...
WARNING: com.github.dataJAR-recipes.pkg.VMware Fusion 11 is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2810, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2804, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2323, in run_recipes
    autopackager.verify(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 606, in verify
    step["Processor"], recipe=recipe, env=self.env
  File "/Library/AutoPkg/autopkglib/__init__.py", line 822, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/DittoCopier.py", line 60
    raise ProcessorError(f"Can't remove {dest_item}: {err.strerror}")
                                                                   ^
SyntaxError: invalid syntax
username@computername VMWareFusion %
```

**Comment by macmule** [comment]
@mikedowler quick q.. what version of Python was "DittoCopier.py" tested against?

**Comment by rtrouton** [comment]
Disregard, I just noticed I was running an older version of AutoPkg. Updated to AutoPkg 2.1 and now it's fine.

**Comment by macmule** [comment]
Woot! Thanks @rtrouton.. off the hook @mikedowler
