### ISSUE TITLE
Syntax error in DittoCopier.py when

### ISSUE THREAD

**Issue by kitzy** [autopkg/dataJAR-recipes#106]
```
Error log for AutoPkg run
05:38
Traceback (most recent call last):
05:38
File '/usr/local/bin/autopkg', line 2810, in <module>
05:38
sys.exit(main(sys.argv))
05:38
File '/usr/local/bin/autopkg', line 2804, in main
05:38
exit(subcommands[verb]['function'](argv))
05:38
File '/usr/local/bin/autopkg', line 2323, in run_recipes
05:38
autopackager.verify(recipe)
05:38
File '/Library/AutoPkg/autopkglib/__init__.py', line 606, in verify
05:38
step['Processor'], recipe=recipe, env=self.env
05:38
File '/Library/AutoPkg/autopkglib/__init__.py', line 822, in get_processor
05:38
_tmp = imp.load_source(processor_name, processor_filename)
05:38
File '/Users/autopkg/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/DittoCopier.py', line 60
05:38
raise ProcessorError(f'Can't remove {dest_item}: {err.strerror}')
05:38
^
05:38
SyntaxError: invalid syntax
05:38
End of error log for AutoPkg run
```

**Comment by kitzy** [comment]
Here is the recipe override we're using:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.VMware Fusion 11</string>
	<key>Input</key>
	<dict>
		<key>ALL_COMPUTERS</key>
		<string>true</string>
		<key>CUSTOM_TRIGGER</key>
		<string>install-vmware-fusion</string>
		<key>DESCRIPTION</key>
		<string>VMware Fusion gives Mac users the power to run Windows on Mac along with hundreds of other operating systems side by side with Mac applications, without rebooting.</string>
		<key>FORCE_USERS_TO_VIEW_DESCRIPTION</key>
		<string>false</string>
		<key>GROUP_NAME</key>
		<string></string>
		<key>GROUP_TEMPLATE</key>
		<string></string>
		<key>NAME</key>
		<string>VMware Fusion</string>
		<key>POLICY_CATEGORY</key>
		<string>Virtual Machines</string>
		<key>POLICY_NAME</key>
		<string>Employee Machines - %NAME%</string>
		<key>POLICY_TEMPLATE</key>
		<string>/Users/autopkg/Library/AutoPkg/RecipeOverrides/PolicyTemplate-self_service.xml</string>
		<key>RUN_COMMAND</key>
		<string>jamf policy -event license-fusion</string>
		<key>SELF_SERVICE_DISPLAY_NAME</key>
		<string>%NAME%</string>
		<key>SITE_ID</key>
		<string>6</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.dataJAR-recipes.jss.VMWare Fusion 11</string>
	<key>ParentRecipeTrustInfo</key>
	<dict>
		<key>non_core_processors</key>
		<dict>
			<key>DittoCopier</key>
			<dict>
				<key>git_hash</key>
				<string>b343bb0187d06f5bf27382d58e86acf07692b7ce</string>
				<key>path</key>
				<string>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/DittoCopier.py</string>
				<key>sha256_hash</key>
				<string>d95f43b697a5c07f2e201a0f6bf39553564a47540a6d9e08f314e7cab603b22c</string>
			</dict>
		</dict>
		<key>parent_recipes</key>
		<dict>
			<key>com.github.dataJAR-recipes.download.VMware Fusion 11</key>
			<dict>
				<key>git_hash</key>
				<string>55e5f1c332b79c9a9ed0f1ed5465dd6b4fca6113</string>
				<key>path</key>
				<string>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/VMware Fusion 11.download.recipe</string>
				<key>sha256_hash</key>
				<string>778703fd7a464a9deb5fe8efa35c54ce993f30d69375efb5e28ca8c0ddb3d346</string>
			</dict>
			<key>com.github.dataJAR-recipes.jss.VMWare Fusion 11</key>
			<dict>
				<key>git_hash</key>
				<string>9072012c544e8569bced8b37626ee0b6f446c7ef</string>
				<key>path</key>
				<string>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/VMware Fusion 11.jss.recipe</string>
				<key>sha256_hash</key>
				<string>01cc07a3dc866d21141a71ea6111bf4df43a8028cf78fba6ae0fa5dbe42763d8</string>
			</dict>
			<key>com.github.dataJAR-recipes.pkg.VMware Fusion 11</key>
			<dict>
				<key>git_hash</key>
				<string>ffc539c571e2238b986ca35da215fccad5105efa</string>
				<key>path</key>
				<string>~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/VMware Fusion 11.pkg.recipe</string>
				<key>sha256_hash</key>
				<string>b5d411790c68145563cf432b19a10d2316f24545ef340d7467c7d4af3dc1e6f4</string>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
```

**Comment by neilmartin83** [comment]
Heya,

Could you please post the output of `autopkg run -vvv /path/to/your/override`?

The DittoCopier is used in the pkg recipe and I ran that just fine here.

What version of AutoPkg are you running? I've tested in 2.1 and 2.2.

Thank you.

**Comment by kitzy** [comment]
@neilmartin83 

Here's the output you requested.

```
$ autopkg run -vvv RecipeOverrides/VMware\ Fusion\ 11.jss.recipe
Processing RecipeOverrides/VMware Fusion 11.jss.recipe...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2810, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2804, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2323, in run_recipes
    autopackager.verify(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 606, in verify
    step["Processor"], recipe=recipe, env=self.env
  File "/Library/AutoPkg/autopkglib/__init__.py", line 822, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Users/autopkg/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 11/DittoCopier.py", line 60
    raise ProcessorError(f"Can't remove {dest_item}: {err.strerror}")
                                                                   ^
SyntaxError: invalid syntax
```

**Comment by kitzy** [comment]
Turns out I was using outdated versions of Autopkg and jssimporter. I updated both and now its working as expcted.
