### ISSUE TITLE
Vmware Fusion 12 download recipe erroring

### ISSUE THREAD

**Issue by rtrouton** [autopkg/dataJAR-recipes#209]
I'm seeing an error when running `VMware Fusion 12.download.recipe`:

```
No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY
```

Full verbose output below:

```
username@computername ~ % autopkg run "com.github.dataJAR-recipes.download.VMware Fusion 12" -vvvv
Processing com.github.dataJAR-recipes.download.VMware Fusion 12...
WARNING: com.github.dataJAR-recipes.download.VMware Fusion 12 is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'API_PASSWORD': 'api_password_here',
 'API_USERNAME': 'api_username_here',
 'AUTOPKG_VERSION': '2.3.1',
 'JSS_URL': 'https://jamf.pro.server.here',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/username/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.VMware '
                     'Fusion 12',
 'RECIPE_DIR': '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware '
               'Fusion 12',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware '
                'Fusion 12/VMware Fusion 12.download.recipe',
 'RECIPE_REPOS': {'/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.Yohan460-recipes': {'URL': 'https://github.com/autopkg/Yohan460-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes': {'URL': 'https://github.com/autopkg/andrewvalentine-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes': {'URL': 'https://github.com/autopkg/apettinen-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes': {'URL': 'https://github.com/autopkg/apizz-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.bkerns-recipes': {'URL': 'https://github.com/autopkg/bkerns-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.bnpl-recipes': {'URL': 'https://github.com/autopkg/bnpl-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes': {'URL': 'https://github.com/autopkg/cgerke-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes': {'URL': 'https://github.com/autopkg/foigus-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.golbiga-recipes': {'URL': 'https://github.com/autopkg/golbiga-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes': {'URL': 'https://github.com/autopkg/grahamgilbert-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes': {'URL': 'https://github.com/autopkg/grahampugh-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes': {'URL': 'https://github.com/autopkg/hansen-m-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes': {'URL': 'https://github.com/autopkg/homebysix-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes': {'URL': 'https://github.com/autopkg/jleggat-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes': {'URL': 'https://github.com/autopkg/justinrummel-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes': {'URL': 'https://github.com/autopkg/killahquam-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes': {'URL': 'https://github.com/autopkg/moofit-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes': {'URL': 'https://github.com/autopkg/mosen-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes': {'URL': 'https://github.com/autopkg/n8felton-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes': {'URL': 'https://github.com/autopkg/novaksam-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.patgmac-recipes': {'URL': 'https://github.com/autopkg/patgmac-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.paul-cossey-recipes': {'URL': 'https://github.com/autopkg/paul-cossey-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.peshay-recipes': {'URL': 'https://github.com/autopkg/peshay-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes': {'URL': 'https://github.com/autopkg/rustymyers-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes': {'URL': 'https://github.com/autopkg/scriptingosx-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes': {'URL': 'https://github.com/autopkg/smithjw-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.tbridge-recipes': {'URL': 'https://github.com/autopkg/tbridge-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes': {'URL': 'https://github.com/autopkg/timsutton-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.triti-recipes': {'URL': 'https://github.com/autopkg/triti-recipes'},
                  '/Users/username/Library/AutoPkg/RecipeRepos/com.github.rtrouton.autopkg_recipes': {'URL': 'https://github.com/rtrouton/autopkg_recipes'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.bkerns-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.bnpl-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.cgerke-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.golbiga-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.homebysix-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.jleggat-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.justinrummel-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.killahquam-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.scriptingosx-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.smithjw-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.tbridge-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.timsutton-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.rtrouton.autopkg_recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.peshay-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.patgmac-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.triti-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.paul-cossey-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.Yohan460-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.andrewvalentine-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes',
                        '/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes'],
 'verbose': 4}
URLTextSearcher
{'Input': {'re_pattern': '{\\"name\\":\\"VMware Fusion '
                         '12.*\\",\\"dlgList":\\[{".*",\\"code\\":\\"(?P<downloadGroup>FUS-[\\d]+?)\\",\\"releaseDate\\":\\".*\\",\\"productId\\":\\".*\\",\\"releasePackageId\\":\\".*\\",\\"orderId\\":.*}',
           'url': 'https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY']
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY
Failed.
Receipt written to /Users/username/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.VMware Fusion 12/receipts/com.github.dataJAR-recipes.download-receipt-20220311-181118.plist

The following recipes failed:
    com.github.dataJAR-recipes.download.VMware Fusion 12
        Error in com.github.dataJAR-recipes.download.VMware Fusion 12: Processor: URLTextSearcher: Error: No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY

Nothing downloaded, packaged or imported.
username@computername ~ % 
```

**Comment by rtrouton** [comment]
When connecting to https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY in a browser, the following output is received:

````
{"dlgEditionsLists":[{"name":"VMware Fusion 12.2.3","dlgList":[{"name":"VMware Fusion 12.2.3 (for Intel-based Macs)","code":"FUS-1223-NEW","releaseDate":"2022-03-10T08:00:00Z","productId":"1040","releasePackageId":"86083","orderId":2}],"orderId":0}]}
````

**Comment by dan-snelson** [comment]
We, too, are observing the same issue:

```
% autopkg version
2.4.1

% autopkg run -vv "VMware Fusion 12-Testing.pkg.recipe"
Processing VMware Fusion 12-Testing.pkg.recipe...
URLTextSearcher
{'Input': {'re_pattern': '{\\"name\\":\\"VMware Fusion '
                         '12.*\\",\\"dlgList":\\[{".*",\\"code\\":\\"(?P<downloadGroup>FUS-[\\d]+?)\\",\\"releaseDate\\":\\".*\\",\\"productId\\":\\".*\\",\\"releasePackageId\\":\\".*\\",\\"orderId\\":.*}',
           'url': '[https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY'}}](https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY%27}})
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY
Failed.
Receipt written to /Users/ladmin/Library/AutoPkg/Cache/local.pkg.VMware Fusion 12-Testing/receipts/VMware Fusion 12-Testing.pkg-receipt-20220316-054816.plist

The following recipes failed:
    VMware Fusion 12-Testing.pkg.recipe
        Error in local.pkg.VMware Fusion 12-Testing: Processor: URLTextSearcher: Error: No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY

Nothing downloaded, packaged or imported.
```

[https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_[…]ting&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY](https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY)

`{"dlgEditionsLists":[{"name":"VMware Fusion 12.2.3","dlgList":[{"name":"VMware Fusion 12.2.3 (for Intel-based Macs)","code":"FUS-1223-NEW","releaseDate":"2022-03-10T08:00:00Z","productId":"1040","releasePackageId":"86083","orderId":2}],"orderId":0}]}`

**Comment by Chalcahuite** [comment]
Chiming in, with a me too. Not sure if it's relevant, since it's been quite a while since I've needed to actually download Fusion, but downloading the .dmg and feeding it to the recipe with `autopkg run -vv -p ~/Downloads/VMware-Fusion-12.2.3-19436697_x86.dmg 'VMWare Fusion 12.jss'` also fails. Output doesn't seem to recognize that I've supplied a file:

> autopkg run -vv -p ~/Downloads/VMware-Fusion-12.2.3-19436697_x86.dmg 'VMWare Fusion 12.jss'
Processing VMWare Fusion 12.jss...
WARNING: VMWare Fusion 12.jss is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '{\\"name\\":\\"VMware Fusion '
                         '12.*\\",\\"dlgList":\\[{".*",\\"code\\":\\"(?P<downloadGroup>FUS-[\\d]+?)\\",\\"releaseDate\\":\\".*\\",\\"productId\\":\\".*\\",\\"releasePackageId\\":\\".*\\",\\"orderId\\":.*}',
           'url': 'https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY
Failed.
Receipt written to /Users/savile200/Library/AutoPkg/Cache/com.github.dataJAR-recipes.jss.VMWare Fusion 12/receipts/VMWare Fusion 12-receipt-20220321-173922.plist
The following recipes failed:
    VMWare Fusion 12.jss
        Error in com.github.dataJAR-recipes.jss.VMWare Fusion 12: Processor: URLTextSearcher: Error: No match found on URL: https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList?locale=en_US&category=desktop_end_user_computing&product=vmware_fusion&version=12_0&dlgType=PRODUCT_BINARY
Nothing downloaded, packaged or imported.

Unless that's part of the problem. Opening the .dmg there isn't a package inside, it's an installer app.

**Comment by macmule** [comment]
@Chalcahuite, @dan-snelson and @rtrouton the .download was updated earlier today.. is this now resolved?

**Comment by dan-snelson** [comment]
Confirmed resolved, @macmule; thanks big bunches!

**Comment by macmule** [comment]
Awesome, thanks folks!
