### ISSUE TITLE
DisplayLink_Manager.munki failing to extract new content

### ISSUE THREAD

**Issue by eshirk** [autopkg/dataJAR-recipes#252]
With the addition of the Login Screen Extension to the DisplayLink_Manager.download recipe (https://github.com/autopkg/smithjw-recipes/commit/56de71cfbc88cde28ecad9987385dd51ee79fe33), the Munki recipe is having trouble extracting the new extension:

Processor: FlatPkgUnpacker: Error: extraction of /Users/Shared/AutoPkg/Cache/local.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg with pkgutil failed: Could not open package for expansion: /Users/Shared/AutoPkg/Cache/local.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg

(Apologies if this issue should properly be directed at the download recipe maintainer.)

**Comment by smithjw** [comment]
@eshirk @paul-cossey Hey folks, this issue is due to my .download recipe now downloading both the installer and the login window pkg. The dmg for the login window extension is downloaded last which is probably getting sucked up into the munki recipe.

My pkg recipe now combines those two installers into one and creates a new pkg that installs both at the same time. This ensures that the end-user no longer needs to installed the additional login window pkg for external displays to work.

**Comment by paul-cossey** [comment]
Thanks, @eshirk and @smithjw 

I'll take a look at this today :-)

**Comment by paul-cossey** [comment]
Sorry for the delay in getting to this, @eshirk, could you try this commit: https://github.com/autopkg/dataJAR-recipes/commit/32125d8f32d5087b08dd86ccc20e399752d3b820 and let me know if it works for you please?

Thanks for the work on the pkg recipe, @smithjw 

:-)

**Comment by eshirk** [comment]
Thanks, @paul-cossey; we've got progress now in that the download is no longer failing, but one of the shared processors is generating an error:

Traceback (most recent call last):
  File "/Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/Shared Processors/XPathParser.py", line 92, in main
    xml_info = tree.findall(xpath)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.MLBZ521-recipes/Shared Processors/XPathParser.py", line 99, in main
    raise ProcessorError(f"Can't parse xml file {xml_file}: {error.strerror}") from error
AttributeError: 'IndexError' object has no attribute 'strerror'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
'IndexError' object has no attribute 'strerror'
Failed.
Receipt written to /Users/Shared/AutoPkg/Cache/local.munki.DisplayLink Manager/receipts/displaylink_manager-receipt-20221012-111524.plist

The following recipes failed:
    displaylink_manager.munki
        Error in local.munki.DisplayLink Manager: Processor: com.github.mlbz521.SharedProcessors/XPathParser: Error: 'IndexError' object has no attribute 'strerror'

**Comment by paul-cossey** [comment]
Have you updated repos, @eshirk? It's working for me:

```
autopkg run -v /Users/paul/Downloads/smithjw-recipes-master/DisplayLink/DisplayLink\ Manager.munki.recipe
Processing /Users/paul/Downloads/smithjw-recipes-master/DisplayLink/DisplayLink Manager.munki.recipe...
WARNING: /Users/paul/Downloads/smithjw-recipes-master/DisplayLink/DisplayLink Manager.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (match): /node/4711?filetype=exe
URLTextSearcher
URLTextSearcher: Found matching text (download_url): /sites/default/files/exe_files/2022-07/DisplayLink%20Manager%20Graphics%20Connectivity1.7.1-EXE.pkg
URLTextSearcher: Found matching text (match): /sites/default/files/exe_files/2022-07/DisplayLink%20Manager%20Graphics%20Connectivity1.7.1-EXE.pkg
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 05 Jul 2022 15:23:10 GMT
URLDownloader: Downloaded /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager.pkg
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 02 Jun 2021 10:26:40 GMT
URLDownloader: Downloaded /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg
FileFinder
FileFinder: Mounted disk image /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg
FileFinder: Found file match: '/private/tmp/dmg.lbEiZD/DisplayLinkLoginScreenExtension.pkg' from globbed '/private/tmp/dmg.lbEiZD/*.pkg'
FileFinder: DMG-relative file match: 'DisplayLinkLoginScreenExtension.pkg'
FileFinder: Basename match: 'DisplayLinkLoginScreenExtension.pkg'
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "DisplayLink_Manager.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2022-07-04 13:57:21 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: DisplayLink Corp (73YQY62QM3)
CodeSignatureVerifier:        Expires: 2023-01-03 14:56:39 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            AD 0C 45 66 01 17 45 F1 6C 41 91 21 E3 70 15 6C 49 7C 4B 15 ED 21 
CodeSignatureVerifier:            2D 6D BA 77 1C 98 79 12 6F 8A
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "DisplayLinkLoginScreenExtension.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2021-05-24 09:25:16 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: DisplayLink Corp (73YQY62QM3)
CodeSignatureVerifier:        Expires: 2023-01-03 14:56:39 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            AD 0C 45 66 01 17 45 F1 6C 41 91 21 E3 70 15 6C 49 7C 4B 15 ED 21 
CodeSignatureVerifier:            2D 6D BA 77 1C 98 79 12 6F 8A
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
PkgRootCreator
PkgRootCreator: Created /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager
PkgRootCreator: Created /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/Scripts
PkgRootCreator: Created /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/pkgroot
com.github.mlbz521.SharedProcessors/XarExtractSingleFile
XarExtractSingleFile: extracted_file:  /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/extractedfile/Distribution
com.github.mlbz521.SharedProcessors/XPathParser
XPathParser: attribute_one:  1.7.1
com.github.mlbz521.SharedProcessors/XPathParser
XPathParser: attribute_one:  11.0
PkgCopier
PkgCopier: Copied /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager.pkg to /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/Scripts/DisplayLink_Manager-1.7.1.pkg
PkgCopier
PkgCopier: Mounted disk image /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg
PkgCopier: Copied /private/tmp/dmg.PbHfzP/DisplayLinkLoginScreenExtension.pkg to /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/Scripts/DisplayLink_Manager_Extension-1.7.1.pkg
FileCreator
FileCreator: Created file at /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/Scripts/preinstall
PkgCreator
PkgCreator: Package already exists at path /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager-1.7.1.pkg.
PkgCreator: Existing package matches version and identifier, not building.
com.github.smithjw.processors/FriendlyPathDeleter
FriendlyPathDeleter: Deleted /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager
FriendlyPathDeleter: Deleted /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/extractedfile
FlatPkgUnpacker
FlatPkgUnpacker: Unpacked /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager.pkg to /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/unpack
PkgPayloadUnpacker
PkgPayloadUnpacker: Unpacked /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/unpack/DisplayLinkManagerApp.pkg/Payload to /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink Manager/Applications
MunkiInstallsItemsCreator
MunkiInstallsItemsCreator: Created installs item for /Applications/DisplayLink Manager.app
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'installs': [{'CFBundleIdentifier': 'com.displaylink.DisplayLinkUserAgent', 'CFBundleName': 'DisplayLinkUserAgent', 'CFBundleShortVersionString': '1.7.1', 'CFBundleVersion': '129', 'minosversion': '11.0', 'path': '/Applications/DisplayLink Manager.app', 'type': 'application', 'version_comparison_key': 'CFBundleShortVersionString'}]} into pkginfo
PlistReader
PlistReader: Reading: /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink Manager/Applications/DisplayLink Manager.app/Contents/Info.plist
PlistReader: Assigning value of '1.7.1' to output variable 'version'
PlistReader: Assigning value of '11.0' to output variable 'min_os_version'
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'minimum_os_version': '11.0', 'version': '1.7.1'} into pkginfo
MunkiImporter
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:         plugin: FileRepo
MunkiImporter:           repo: /Users/Shared/munki_repo
MunkiImporter: Copied pkginfo to: /Users/Shared/munki_repo/pkgsinfo/apps/DisplayLink Manager/DisplayLink Manager-1.7.1.plist
MunkiImporter:            pkg to: /Users/Shared/munki_repo/pkgs/apps/DisplayLink Manager/DisplayLink_Manager-1.7.1.pkg
PathDeleter
PathDeleter: Deleted /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink Manager
PathDeleter: Deleted /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/unpack
PathDeleter: Deleted /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads
Receipt written to /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/receipts/DisplayLink Manager.munki-receipt-20221012-174036.plist

The following new items were downloaded:
    Download Path                                                                                                                       
    -------------                                                                                                                       
    /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager.pkg            
    /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/downloads/DisplayLink_Manager_Extension.dmg  

The following packages were copied:
    Pkg Path                                                                                                                                                    
    --------                                                                                                                                                    
    /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/Scripts/DisplayLink_Manager-1.7.1.pkg            
    /Users/paul/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.DisplayLink Manager/DisplayLink_Manager/Scripts/DisplayLink_Manager_Extension-1.7.1.pkg  

The following new items were imported into Munki:
    Name                 Version  Catalogs  Pkginfo Path                                              Pkg Repo Path                                           Icon Repo Path  
    ----                 -------  --------  ------------                                              -------------                                           --------------  
    DisplayLink Manager  1.7.1    testing   apps/DisplayLink Manager/DisplayLink Manager-1.7.1.plist  apps/DisplayLink Manager/DisplayLink_Manager-1.7.1.pkg
```

**Comment by eshirk** [comment]
Still failing for me, @paul-cossey, and I did update repos and also deleted/re-added both data-JAR and smithjw repos. 

But maybe I've misunderstood your commit. I'm testing a new override for com.github.dataJAR-recipes.munki.DisplayLink Manager; should I take a different approach?

**Comment by paul-cossey** [comment]
Do you have MLBZ521's repo added/updated? As that's where the processor that's erroring is.

**Comment by eshirk** [comment]
Yes, I ran repo-update all and confirmed all repos were up to date, but also deleted/readded MLBZ521 for good measure. Still the same error.

Overriding and running com.github.smithjw.pkg.DisplayLink_Manager results in a successful pkg download, no errors. But running the  dataJAR Munki recipe against that pkg yields the same error about the com.github.mlbz521.SharedProcessors/XPathParser processor.

**Comment by smithjw** [comment]
@eshirk just to make sure all bases are covered, have you tried deleting all the trust information from your override of the .munki recipe and then updating trust on it again. That should hopefully ensure all the relevant parents are in use and trusted.

**Comment by eshirk** [comment]
Good thought @smithjw, but I deleted all 3 repos as well as the .munki override, dumped caches, readded the repos, and created a new override.

If I'm the only one seeing this issue, it's clearly something in my environment.

**Comment by paul-cossey** [comment]
What version of AutoPkg are you running, @eshirk?

**Comment by eshirk** [comment]
Oh yikes--we're still on 2.4.1.... Didn't realize we'd fallen that far behind! I'll work on getting that updated, then test again. Feel free to close this issue in the meantime.

**Comment by paul-cossey** [comment]
I'm pretty sure that's the issue then. I'll close this off, but please feel free to reopen if you're still having issues after updating.

**Comment by eshirk** [comment]
@paul-cossey and @smithjw: I'm afraid that after an AutoPkg update to v2.7, and subsequently removing and readding all three involved repos/making a new override/dumping the recipe cache, I'm getting the same IndexError.

You said above that smithjw-recipes-master/DisplayLink/DisplayLink Manager.munki.recipe works for you, but I can't find that recipe. Are you able to successfully run com.github.dataJAR-recipes.munki.DisplayLink Manager?

And thank you both for your assistance with this issue.

**Comment by Frzk** [comment]
FWIW, I'm experiencing the same with autopkg 2.7:

> Processing DisplayLink Manager.munki...
> 'IndexError' object has no attribute 'strerror'
> Failed.

**Comment by eshirk** [comment]
Checking in again on this closed issue...com.github.dataJAR-recipes.munki.DisplayLink Manager is still throwing a 'list index out of range' error for me.

@Frzk , are you seeing the same?

I can open a new issue if that's preferred.

**Comment by Frzk** [comment]
Hey @eshirk,
Yes, I'm still seeing the same (and unfortunately got no time to investigate further).

**Comment by paul-cossey** [comment]
Feel free to reopen this if you're still having issues (we're not). I can take another look tomorrow all being well.

**Comment by eshirk** [comment]
Thanks, @paul-cossey! I'll open a new issue since the base issue has changed.
