### ISSUE TITLE
Lens.download.recipe - No match found on URL

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#269]
Heya folks,
Thought I'd raise this so it's on the radar. It looks like the Lens download recipe/s are failing on unable to find a match on the URL

```
The following recipes failed:
    /Users/Darren.Wallace/git/it-endpoint-mac-autopkg-recipes/Lens/Lens-ARM.pkg.recipe.yaml
        Error in [domain].recipes.pkg.Lens-ARM: Processor: URLTextSearcher: Error: No match found on URL: https://lens-binaries.s3.amazonaws.com/ide/latest-mac.yml
```

I'll try and get some time to look into this later today but if not, I thought I'd chuck it on your radar too :) 

Cheers!

**Comment by paul-cossey** [comment]
Thanks for raising, @Daz-wallace 

I've had a quick look this afternoon, looks like they're having issues with the update feed. 

Can't use the main website as its Java Script. and the GitHub release numbers don't match up with the Desktop client. 

I can see in ~/Library/Logs/OpenLens/lens.log that the app is failing see the feed too. 

```
error: [UPDATE-APP/CHECK-FOR-UPDATES] Cannot find channel "latest-mac.yml" update info: HttpError: 404 

at SimpleURLLoaderWrapper.emit (node:domain:475:12) {"code":"ERR_UPDATER_CHANNEL_FILE_NOT_FOUND","stack":"Error: Cannot find channel \"latest-mac.yml\" update info: HttpError: 404 \n\"method: GET url: https://github.com/MuhammedKalkan/OpenLens/releases/download/Latest/latest-mac.yml?noCache=1glfb73af\\n\\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\\n\"\nHeaders: {\n  \"server\": \"GitHub.com\",\n  \"date\": \"Thu, 29 Dec 2022 16:25:03 GMT\",\n  \"content-type\": \"text/plain; charset=utf-8\",\n  \"vary\": \"X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With\",\n  \"cache-control\": \"no-cache\",\n  \"strict-transport-security\": \"max-age=31536000; includeSubdomains; preload\",\n  \"x-frame-options\": \"deny\",\n  \"x-content-type-options\": \"nosniff\",\n  \"x-xss-protection\": \"0\",\n  \"referrer-policy\": \"no-referrer-when-downgrade\",\n  \"content-security-policy\": \"default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'\",\n  \"content-encoding\": \"gzip\",\n  \"content-length\": \"29\",\n  \"x-github-request-id\": \"C118:FFC3:405A9E2:42AC4DF:63ADBF5F\"\n}\n    at createHttpError (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)\n    at ElectronHttpExecutor.handleResponse (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)\n    at ClientRequest.<anonymous> (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)\n    at ClientRequest.emit (node:events:526:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)\n    at SimpleURLLoaderWrapper.emit (node:domain:475:12)\n    at Object.newError (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)\n    at GenericProvider.getLatestVersion (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GenericProvider.js:27:50)\n    at async MacUpdater.getUpdateInfoAndProvider (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:298:19)\n    at async MacUpdater.doCheckForUpdates (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:312:24)\n    at async /private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/static/build/main.js:2:414107\n    at async r (/private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/static/build/main.js:2:414597)\n    at async /private/var/folders/n3/xml09j416v16wb14zb299lwr0000gp/T/AppTranslocation/9B0B7D4F-8669-412B-BAB7-0087F4466CBA/d/OpenLens.app/Contents/Resources/app.asar/static/build/main.js:2:417261"}
```

I'm off now until Monday, maybe feed will magically start working by then? 🤔

**Comment by paul-cossey** [comment]
If you folks pay for a licence may be worth raising a support ticket with the vendor? 😄

**Comment by Daz-wallace** [comment]
Hmm I'm not able to recreate the issue in the GUI when using the previous version I have (v2022.9.280635 - ARM). It sees the 2023.x update fine and installs fine (after admin prompt). No messages in the log regarding update fails.
I'll do some more digging...

**Comment by Daz-wallace** [comment]
So I might have something...

- Inside the App bundle there is this file `/Applications/Lens.app/Contents/Resources/app-update.yml`
- This contains the below info:
 > provider: generic
url: https://downloads.k8slens.dev/ide
channel: latest
updaterCacheDirName: lens-updater
- I combined this with your URL from the current recipe to use "https://downloads.k8slens.dev/ide/latest-mac.yml"
- This seems to pull down the info we're after!
- So I'm looking at the following changes, let me know if you agree:

- https://github.com/autopkg/dataJAR-recipes/blob/master/Lens/Lens.download.recipe#L18
- `        <string>https://downloads.k8slens.dev/ide/latest-mac.yml</string>`
- https://github.com/autopkg/dataJAR-recipes/blob/master/Lens/Lens.download.recipe#L54
- `                <string>https://downloads.k8slens.dev/ide/%version%</string>`
- Maybe it's worth variablesing the download URL too?

Let me know what you think when you get a chance to look into it

**Comment by Daz-wallace** [comment]
PR logged :) 
Tests good for me both with `ARCHITECTURE` set to no value, and to `-arm64`

**Comment by paul-cossey** [comment]
Lovely, stuff. Thanks!

Testing works for me too
