### ISSUE TITLE
403 error when using URLDownloader for Noun Project.download.recipe

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#282]
Hey folks,

Seeing a 403 error when trying to use the Noun Project download recipe. Not had a chance to dig in properly yet but thought I'd get the issue logged so it's on your radar too.

Full (redacted) output:
```% autopkg run -vvv "com.github.dataJAR-recipes.download.Noun Project"
Processing com.github.dataJAR-recipes.download.Noun Project...
WARNING: com.github.dataJAR-recipes.download.Noun Project is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'AUTOPKG_VERSION': '2.7',
 'NAME': 'NounProject',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/Darren.Wallace/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.Noun '
                     'Project',
 'RECIPE_DIR': '/Users/Darren.Wallace/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Noun '
               'Project',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/Darren.Wallace/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Noun '
                'Project/Noun Project.download.recipe',
 'RECIPE_REPOS': [redacted]
 'RECIPE_SEARCH_DIRS': [redacted]
 'SPARKLE_FEED_URL': 'https://thenounproject.com/for-mac/feed/',
 'jsm_webhook_url': 'https://automation.atlassian.com/pro/hooks/b706c5e38df03d2e18374e43680d28098d98c76c',
 'verbose': 3}
SparkleUpdateInfoProvider
{'Input': {'appcast_url': 'https://thenounproject.com/for-mac/feed/'}}
SparkleUpdateInfoProvider: Version retrieved from appcast: 641
SparkleUpdateInfoProvider: User-facing version retrieved from appcast: 2.2.5
SparkleUpdateInfoProvider: Found URL https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip
{'Output': {'url': 'https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip',
            'version': '2.2.5'}}
URLDownloader
{'Input': {'url': 'https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: ERROR: (22) The requested URL returned error: 403

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 172, in execute_curl
    result = subprocess.run(
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip', '--fail', '--output', '/Users/Darren.Wallace/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.Noun Project/downloads/tmp0a5ye3dj']' returned non-zero exit status 22.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 331, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 186, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 181, in execute_curl
    raise ProcessorError(e.stderr) from e
autopkglib.ProcessorError: curl: (22) The requested URL returned error: 403

  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
curl: (22) The requested URL returned error: 403

Failed.
Receipt written to /Users/Darren.Wallace/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.Noun Project/receipts/com.github.dataJAR-recipes.download-receipt-20230406-085120.plist

The following recipes failed:
    com.github.dataJAR-recipes.download.Noun Project
        Error in com.github.dataJAR-recipes.download.Noun Project: Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 403

Nothing downloaded, packaged or imported.
```

The same URL in Safari (https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip) also shows a 403, so maybe this is a vender issue?

**Comment by macmule** [comment]
The sparkle feed: https://thenounproject.com/for-mac/feed/, does point to https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip.. and as mentioned that 403's..

However, it also has a publication date of: `2019-10-07 00:00:00 UTC`

So, I guess this is no longer a valid URL to get the download from.

We'd need to get a copy of the latest app and pull it apart

**Comment by macmule** [comment]
..and creating an account and downloading the latest version is indeed the 2019 version, but instead of https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.zip it's https://nounproject.s3.amazonaws.com/mac/Noun-Project-2.2.5.dmg..

so, yep.. vendor issue

**Comment by Daz-wallace** [comment]
Was part way through the same discovery and you beat me to it :)

**Comment by paul-cossey** [comment]
Hi, @Daz-wallace 

I've raised this with the vendor, but for now I've fudged it 😄 

Could you give this a try please? https://github.com/autopkg/dataJAR-recipes/commit/cc7a1e53210e25d7b0dd75350bc1fe88dab55ce9

**Comment by Daz-wallace** [comment]
Heya @paul-cossey 
I'm getting a "No Match on URL error" from the .download in that commit
`URLTextSearcher
{'Input': {'re_pattern': 'url=\\"(https://nounproject\\.s3\\.amazonaws\\.com/mac/Noun-Project-([0-9]+(\\.[0-9]+)+))\\.zip\\"',
           'result_output_var_name': 'DL_URL',
           'url': 'https://thenounproject.com/for-mac/feed/'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://thenounproject.com/for-mac/feed/
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://thenounproject.com/for-mac/feed/
Failed.
Receipt written to /Users/Darren.Wallace/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.Noun Project/receipts/Noun Project.download-receipt-20230411-083536.plist

The following recipes failed:
    /Users/Darren.Wallace/Desktop/Noun Project.download.recipe
        Error in com.github.dataJAR-recipes.download.Noun Project: Processor: URLTextSearcher: Error: No match found on URL: https://thenounproject.com/for-mac/feed/

Nothing downloaded, packaged or imported.`

**Comment by paul-cossey** [comment]
Looks like there is now a static download URL, @Daz-wallace can you give this a try please? https://github.com/autopkg/dataJAR-recipes/commit/af9b754111129b8a0e6590fdce4a1edf625ed465

**Comment by paul-cossey** [comment]
🍻 

Thanks, @Daz-wallace I'll close this off 😄
