### ISSUE TITLE
PostgreSQL 13.download.recipe - No match found on URL

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#334]
Hey folks,

Looks like PostgreSQL have changed the site around a bit. Both the version 13 and 14 recipes are failing on "No match found on URL".

I'm gonna poke and see if I can get a nice PR in, but for now, the error details are:
```URLTextSearcher
{'Input': {'re_pattern': 'Version (13\\.\\d)',
           'url': 'https://www.enterprisedb.com/download-postgresql-binaries'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.enterprisedb.com/download-postgresql-binaries
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://www.enterprisedb.com/download-postgresql-binaries
Failed.
Receipt written to /Users/Darren.Wallace/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.PostgreSQL 13/receipts/com.github.dataJAR-recipes.download-receipt-20240509-084443.plist

The following recipes failed:
    com.github.dataJAR-recipes.download.PostgreSQL 13
        Error in com.github.dataJAR-recipes.download.PostgreSQL 13: Processor: URLTextSearcher: Error: No match found on URL: https://www.enterprisedb.com/download-postgresql-binaries```

**Comment by Daz-wallace** [comment]
Well that's a horrible string to Regex
`[\"Version \",\"13.12\",`

**Comment by Daz-wallace** [comment]
PR in :)

**Comment by paul-cossey** [comment]
PR merged - closing 😄
