### ISSUE TITLE
nodejslts.download.recipe HTTP 412 / curl error 56

### ISSUE THREAD

**Issue by opus-nbonenberger** [autopkg/dataJAR-recipes#376]
Yesterday, the recipe started erroring:

```
URLTextSearcher
{'Input': {'re_pattern': 'node-v22.([0-9]+(\\.[0-9]+)+).pkg',
           'result_output_var_name': 'MINOR_VERSION',
           'url': 'https://nodejs.org/dist/latest-v22.x/'}}
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://nodejs.org/dist/latest-v22.x/']
URLTextSearcher: Found matching text (MINOR_VERSION): 11.0
{'Output': {'MINOR_VERSION': '11.0'}}
URLDownloader
{'Input': {'url': 'https://nodejs.org/dist/latest-v22.x/node-v22.11.0.pkg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: ERROR: (56) The requested URL returned error: 412

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 172, in execute_curl
    result = subprocess.run(
  File "/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://nodejs.org/dist/latest-v22.x/node-v22.11.0.pkg', '--fail', '--output', '/Users/admin/Library/AutoPkg/Cache/local.munki.nodejslts_mod-v22/downloads/tmpkfy85lsy', '--header', 'If-None-Match: "2561fd33654736c5b1347bd4bcbb10ee"', '--header', 'If-Modified-Since: Tue, 29 Oct 2024 04:39:40 GMT']' returned non-zero exit status 56.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLDownloader.py", line 331, in main
    raw_headers = self.download_with_curl(curl_cmd)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 186, in download_with_curl
    proc_stdout, proc_stderr, retcode = self.execute_curl(curl_cmd, text)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 181, in execute_curl
    raise ProcessorError(e.stderr) from e
autopkglib.ProcessorError: curl: (56) The requested URL returned error: 412

  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
curl: (56) The requested URL returned error: 412

Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/local.munki.nodejslts_mod-v22/receipts/local.munki-receipt-20241114-104931.plist

The following recipes failed:
    local.munki.nodejslts_mod-v22
        Error in local.munki.nodejslts_mod-v22: Processor: URLDownloader: Error: curl: (56) The requested URL returned error: 412
```

I tried running the curl command from the output separately and it works. I don't know what the problem is. @paul-cossey can you confirm the issue?

**Comment by paul-cossey** [comment]
Hey, @opus-nbonenberger 

Just ran the recipe on my MacBook and it completed successfully 
```
autopkg run -v nodejslts.munki.recipe
Looking for com.github.dataJAR-recipes.download.nodejslts...
Did not find com.github.dataJAR-recipes.download.nodejslts in recipe map
Rebuilding recipe map with current working directories...
Looking for com.github.dataJAR-recipes.download.nodejslts...
Found com.github.dataJAR-recipes.download.nodejslts in recipe map
**load_recipe time: 0.007038708004984073
Processing nodejslts.munki.recipe...
WARNING: nodejslts.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (MINOR_VERSION): 18.0
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 03 Oct 2024 06:46:10 GMT
URLDownloader: Storing new ETag header: "13c7d19942099854c1ae69b107d1e375"
URLDownloader: Downloaded /Users/paul.cossey/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.nodejslts/downloads/node-v20.18.0.pkg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "node-v20.18.0.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2024-10-03 06:44:41 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Node.js Foundation (HX7739G8FX)
CodeSignatureVerifier:        Expires: 2025-01-22 03:40:11 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            12 88 B9 4D 11 C6 8D 19 9A 3B EC C6 CF 9D 68 8B EA D8 DD 48 05 74 
CodeSignatureVerifier:            52 73 73 47 DE B8 6C BB 27 2F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        Expires: 2027-02-01 22:12:15 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
CodeSignatureVerifier:            F2 9C 88 CF B0 B1 BA 63 58 7F
CodeSignatureVerifier:        ------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        Expires: 2035-02-09 21:40:36 +0000
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
CodeSignatureVerifier:            68 C5 BE 91 B5 A1 10 01 F0 24
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
MunkiImporter
MunkiImporter: Using repo lib: AutoPkgLib
MunkiImporter:         plugin: FileRepo
MunkiImporter:           repo: /Users/Shared/munki_repo
MunkiImporter: Copied pkginfo to: /Users/Shared/munki_repo/pkgsinfo/apps/NodeLTS.js/nodelts-20.18.0.plist
MunkiImporter:            pkg to: /Users/Shared/munki_repo/pkgs/apps/NodeLTS.js/node-v20.18.0.pkg
Receipt written to /Users/paul.cossey/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.nodejslts/receipts/nodejslts.munki-receipt-20241114-100320.plist

The following new items were downloaded:
    Download Path                                                                                                    
    -------------                                                                                                    
    /Users/paul.cossey/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.nodejslts/downloads/node-v20.18.0.pkg  

The following new items were imported into Munki:
    Name     Version  Catalogs  Pkginfo Path                           Pkg Repo Path                      Icon Repo Path  
    ----     -------  --------  ------------                           -------------                      --------------  
    nodelts  20.18.0  testing   apps/NodeLTS.js/nodelts-20.18.0.plist  apps/NodeLTS.js/node-v20.18.0.pkg
```

`56="Failure in receiving network data."` - sounds like a possible issue server side or the local network.

**Comment by paul-cossey** [comment]
Missed the http code on the error 🤦 

![412](https://github.com/user-attachments/assets/6de24ff5-33ad-4209-936f-6e2b7f313311)
https://httpstatusdogs.com/412-precondition-failed 

> [412 Precondition Failed](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Server_Error): The server does not meet one of the preconditions that the requester put on the request.

Which just reinforces the Server side/network issue theory.

**Comment by codeskipper** [comment]
Hi,

We've had this error a lot as well since the end of 2024.  It fails just about every day in our CI pipeline which runs this recipe at about the same time as part of our list.  When troubleshooting, I found it comes and goes, I  haven't been able to find a pattern to how or when it occurs.

After looking up the http code, my understanding from [this answer on Stackoverflow](https://stackoverflow.com/a/5369582/4326287) is that 412 should be taken to mean "no match" for the preconditions, in our case the etag and date.

Here are a couple of examples of where cURL returns the error and where it does not.
```
me@a-mac downloads % /usr/bin/curl --silent --show-error --no-buffer --dump-header - --speed-time 30 --location --url https://nodejs.org/dist/latest-v20.x/node-v20.18.3.pkg --fail --output /Users/$HOME/Library/AutoPkg/Cache/local.ws1.NodeJS-LTS/downloads/tmpd_5k3i_k --header 'If-None-Match: "0241fea6159a179d2f451f3a6171b688"' --header "If-Modified-Since: Mon, 10 Feb 2025 11:50:34 GMT"
HTTP/2 304
date: Thu, 27 Feb 2025 15:10:58 GMT
cf-ray: 91891acd481f5689-OSL
cf-cache-status: HIT
age: 4654
cache-control: public, max-age=3600, s-maxage=14400
etag: "0241fea6159a179d2f451f3a6171b688"
last-modified: Mon, 10 Feb 2025 11:50:34 GMT
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
accept-range: bytes
x-content-type-options: nosniff
server: cloudflare

me@a-mac downloads % /usr/bin/curl --silent --show-error --no-buffer --dump-header - --speed-time 30 --location --url https://nodejs.org/dist/latest-v20.x/node-v20.18.3.pkg --fail --output /Users/$HOME/Library/AutoPkg/Cache/local.ws1.NodeJS-LTS/downloads/tmpd_5k3i_k --header 'If-None-Match: "0241fea6159a179d2f451f3a6171b688"' --header "If-Modified-Since: Mon, 10 Feb 2025 11:50:34 GMT"
HTTP/2 412
date: Fri, 28 Feb 2025 07:18:39 GMT
content-type: application/x-xar
content-length: 0
cache-control: private, no-cache, no-store, max-age=0, must-revalidate
etag: "0241fea6159a179d2f451f3a6171b688"
last-modified: Mon, 10 Feb 2025 11:50:34 GMT
accept-range: bytes
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 918ea44ebff356b5-OSL


curl: (56) The requested URL returned error: 412

```


It seems to me one or some of the vendor servers are configured a little different, so in case of no match for the preconditions, sometimes this error code 412 is retuned, but either way, no new download is started.

Would it be possible to take into account in the recipe that http error 412 may be a valid response meaning "no match" ?

**Comment by codeskipper** [comment]
Newer mind, I just asked ChatGPT and it explained cURL exit code indicates a server/network issue.  

I ran the cURL command again with --verbose as suggested, and the response included 
> process_pending_input: nghttp2_session_mem_recv() returned -902:The user callback function failed


So I'll try reporting it to vendor.

Sorry for stealing your attention.
