### ISSUE TITLE
Issues with Autopkg 2 - BoxDrive - PkgInfo.py

### ISSUE THREAD

**Issue by TSPARR** [autopkg/dataJAR-recipes#55]
This processor fails in Autopkg 2.
```
PkgInfo
{'Input': {}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Users/munki/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/BoxDrive/PkgInfo.py", line 59, in main
    toc = toc.strip().split('\n')
TypeError: a bytes-like object is required, not 'str'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
a bytes-like object is required, not 'str'
Failed.
```

**Comment by macmule** [comment]
thanks, I've moved this to a shared processor & will sort when tackling python 3

**Comment by macmule** [comment]
Sorted, see: https://github.com/autopkg/dataJAR-recipes/commit/fbcf938271b22b8ee63b98d274e3f2cbffc39813

Thanks for your patience!
