### ISSUE TITLE
Getting "module 'FoundationPlist' has no attribute 'readPlistFromString'" error

### ISSUE THREAD

**Issue by jps3** [autopkg/dataJAR-recipes#67]
I had downloaded new Shared Device License installer packages for a number of Adobe Creative Cloud applications today (Wed Feb 12) and have had errors using **Adobe2020Versioner.py** importing all of them into munki.

- autopkg version 2.0.2
- munki version 4.0.1.3899
- dataJAR-recipes commit 2c7e7c93b4e966f565bd3c44c856ed3e311e1108
- macOS 10.14.6 18G3020

```
ladmin$ ~/ghq/github.com/autopkg/dataJAR-recipes/Adobe\ 2020/Adobe2020Importer.py munki
1 Adobe 2020 folder found, creating recipe list...
Looking for pkgs...
Found /Users/ladmin/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg...
Running recipe_list: `/Users/ladmin/Downloads/adobe2020_list.txt`

Running `['/usr/local/bin/autopkg', 'run', '-v', '--recipe-list', '/Users/ladmin/Downloads/adobe2020_list.txt', '--report-plist', '/Users/ladmin/Downloads/adobe2020_report.plist']`...
Processing local.munki.AdobeXD2020...
Adobe2020Versioner
Adobe2020Versioner: pkg /Users/ladmin/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg
Adobe2020Versioner: Processing /Users/ladmin/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/optionXML.xml
Adobe2020Versioner: SAP Code: SPRK
Adobe2020Versioner: Installer is HyperDrive
Adobe2020Versioner: app_json: /Users/ladmin/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/HD/SPRK27.0.12/Application.json
Adobe2020Versioner: Processing HD installer
Adobe2020Versioner: app_launch: [INSTALLDIR]/Adobe XD.app/Contents/MacOS/Adobe XD
Adobe2020Versioner: app_bundle: Adobe XD.app
Adobe2020Versioner: app_path: Adobe XD
Adobe2020Versioner: installed_path: /Applications/Adobe XD/Adobe XD.app
Adobe2020Versioner: display_name: Adobe XD 2020
Adobe2020Versioner: zip_file: coreAssets
Adobe2020Versioner: zip_path: /Users/ladmin/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/HD/SPRK27.0.12/coreAssets.zip
Adobe2020Versioner: bundle_location: [StagingFolder]/mul
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py", line 97, in main
    self.process_installer()
  File "/Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py", line 138, in process_installer
    self.process_hd_installer()
  File "/Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py", line 263, in process_hd_installer
    data = FoundationPlist.readPlistFromString(plist)
AttributeError: module 'FoundationPlist' has no attribute 'readPlistFromString'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
module 'FoundationPlist' has no attribute 'readPlistFromString'
Failed.
Receipt written to /Users/ladmin/Library/AutoPkg/Cache/local.munki.AdobeXD2020/receipts/local.munki-receipt-20200212-163010.plist

The following recipes failed:
    local.munki.AdobeXD2020
        Error in local.munki.AdobeXD2020: Processor: Adobe2020Versioner: Error: module 'FoundationPlist' has no attribute 'readPlistFromString'

Nothing downloaded, packaged or imported.

Report plist saved to /Users/ladmin/Downloads/adobe2020_report.plist.
```

**Comment by jps3** [comment]
Note: I will keep checking other aspects of the mac I am working on in case it's a different issue. In the meantime in case it _is_ related to something that has changed and affects others I wanted to post it now to get it noted. Thank you.

**Comment by macmule** [comment]
Can you try with AutoPkg 1?

I think this might be due to the python 3 requirements of autopkg 2

**Comment by jps3** [comment]
I do not have an autopkg v1 instance immediately at hand, but that would explain why I am seeing that now but not the last time I had used the Adobe2020*.py scripts. I had forgotten that in the intervening days/weeks I had upgraded to autopkg v2.

I will need to set up a VM with autopkg v1 to do the test, likely I will not have a chance to complete the run until tomorrow, but I will try for this evening if I can.

**Comment by jps3** [comment]
```
$ autopkg version; munkiimport --version; (cd dataJAR-recipes/ && git rev-parse --short HEAD)
1.4.1
4.0.1.3899
2c7e7c9

$ ./dataJAR-recipes/Adobe\ 2020/Adobe2020Versioner.py munki
Traceback (most recent call last):
  File "./dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py", line 49, in <module>
    import FoundationPlist
ImportError: No module named FoundationPlist
```

![Screen Shot 2020-02-12 at 5 18 55 PM 2](https://user-images.githubusercontent.com/379162/74382714-e6863680-4dbb-11ea-96b1-b17307425b7a.png)

**Comment by macmule** [comment]
`FoundationPlist` is part of AutoPkg.. so something is off with that install

**Comment by macmule** [comment]
https://github.com/autopkg/keeleysam-recipes/pull/122

**Comment by jps3** [comment]
Ok. I see where and how I misunderstood where the error was coming from now, I think. I was not looking as closely at all of the verbose output, just the Python error. I completely overlooked the `Running ['/usr/local/bin/autopkg', 'run', ...`. (I was already hours-long frustrated with Adobe SDL packaging, having had to rebuild quite a few today because those created yesterday all gave connection errors.) 

Mea culpa! Sorry for the bother.

Feel free to close this if you do not need it for tracking anything on your part.

**Comment by jps3** [comment]
> `FoundationPlist` is part of AutoPkg.. so something is off with that install

When I did the Autopkg 1.4.1 test last evening, I was calling Adobe2020**Versioner**.py _**not**_ Adobe2020Importer.py on the command line. I had been looking at that filename listed in the traceback information and used it as the import command. (OMFG/#facepalm)

- - - 

Now for something completely different, or at least vaguely similar: A **careful** test.

- Testing VM with macOS 10.14.6
- AutoPkg 1.4.1
- Munki 4.0.1.3899

###  Munki 4 + AutoPkg 1.4.1 Setup
```
$ cd ~/Downloads

$ wget https://github.com/munki/munki/releases/download/v4.1.0/munkitools-4.1.0.3914.pkg
$ sudo installer -target / -pkg munkitools-4.1.0.3914.pkg
$ exec $SHELL --login  # reload shell to update env (for PATH)
$ munkiimport --configure
Repo URL (example: afp://munki.example.com/repo): file:///Users/Shared/munki_repo
pkginfo extension (Example: .plist): .plist
pkginfo editor (examples: /usr/bin/vi or TextMate.app; leave empty to not open an editor after import): /usr/bin/vi
Default catalog to use (example: testing): testing
Repo access plugin (defaults to FileRepo): 

$ wget https://github.com/autopkg/autopkg/releases/download/v1.4.1/autopkg-1.4.1.pkg
$ sudo installer -target / -pkg autopkg-1.4.1.pkg
$ mkdir -p /Users/Shared/munki_repo
$ defaults write com.github.autopkg MUNKI_REPO -string '/Users/Shared/munki_repo'

$ autopkg repo-add dataJAR-recipes
Attempting git clone...

Adding /Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
```

### Prepare AdobeXD2020 Package for Import Test
```
$ autopkg make-override -n AdobeXD2020.munki "com.github.dataJAR-recipes.munki.Import Adobe 2020 Title"
Override file saved to /Users/vagrant/Library/AutoPkg/RecipeOverrides/AdobeXD2020.munki.recipe

$ sed -i '' -e 's/SomeAdobe2020Title/AdobeXD2020/' /Users/vagrant/Library/AutoPkg/RecipeOverrides/AdobeXD2020.munki.recipe

$ ditto -xkv /Volumes/VMware\ Shared\ Folders/AdobeCC_SharedDeviceLicenses/AdobeXD2020_en_US_MAC.zip .
Copying /Volumes/VMware Shared Folders/AdobeCC_SharedDeviceLicenses/AdobeXD2020_en_US_MAC.zip 

$ ditto -xk /Volumes/VMware\ Shared\ Folders/AdobeCC_SharedDeviceLicenses/AdobeXD2020_en_US_MAC.zip .
$ ls -F
AdobeXD2020/               AdobeXD2020_en_US_MAC.zip
```

### Adobe2020Importer.py Test
```
$ ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe\ 2020/Adobe2020Importer.py munki 
1 Adobe 2020 folder found, creating recipe list...
Looking for pkgs...
Found /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg...
Running recipe_list: `/Users/vagrant/Downloads/adobe2020_list.txt`

Running `['/usr/local/bin/autopkg', 'run', '-v', '--recipe-list', '/Users/vagrant/Downloads/adobe2020_list.txt', '--report-plist', '/Users/vagrant/Downloads/adobe2020_report.plist']`...
Processing local.munki.AdobeXD2020...
Adobe2020Versioner
Adobe2020Versioner: pkg /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg
Adobe2020Versioner: Processing /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/optionXML.xml
Adobe2020Versioner: SAP Code: SPRK
Adobe2020Versioner: Installer is HyperDrive
Adobe2020Versioner: app_json: /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/HD/SPRK27.0.12/Application.json
Adobe2020Versioner: Processing HD installer
Adobe2020Versioner: app_launch: [INSTALLDIR]/Adobe XD.app/Contents/MacOS/Adobe XD
Adobe2020Versioner: app_bundle: Adobe XD.app
Adobe2020Versioner: app_path: Adobe XD
Adobe2020Versioner: installed_path: /Applications/Adobe XD/Adobe XD.app
Adobe2020Versioner: display_name: Adobe XD 2020
Adobe2020Versioner: zip_file: coreAssets
Adobe2020Versioner: zip_path: /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/HD/SPRK27.0.12/coreAssets.zip
Adobe2020Versioner: bundle_location: [StagingFolder]/mul
Adobe2020Versioner: vers_compare_key: CFBundleShortVersionString
Adobe2020Versioner: staging_folder: mul
Adobe2020Versioner: staging_folder_path: 1/mul/Adobe XD.app/Contents/Info.plist
Adobe2020Versioner: app_version: 27.0.12.6
Adobe2020Versioner: app_bundle: Adobe XD.app
Adobe2020Versioner: additional_pkginfo: {'installs': [{'path': u'/Applications/Adobe XD/Adobe XD.app', 'version_comparison_key': 'CFBundleShortVersionString', 'CFBundleShortVersionString': u'27.0.12.6', 'type': 'application'}], 'minimum_os_version': u'10.13.0', 'display_name': u'Adobe XD 2020'}
DmgCreator
DmgCreator: Created dmg from /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg at /Users/vagrant/Library/AutoPkg/Cache/local.munki.AdobeXD2020/AdobeXD2020_Install-27.0.12.6.dmg
DmgCreator
DmgCreator: Created dmg from /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Uninstall.pkg at /Users/vagrant/Library/AutoPkg/Cache/local.munki.AdobeXD2020/AdobeXD2020_Uninstall-27.0.12.6.dmg
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'installs': [{'path': u'/Applications/Adobe XD/Adobe XD.app', 'version_comparison_key': 'CFBundleShortVersionString', 'CFBundleShortVersionString': u'27.0.12.6', 'type': 'application'}], 'minimum_os_version': u'10.13.0', 'display_name': u'Adobe XD 2020'} into pkginfo
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {
    version = "27.0.12.6";
} into pkginfo
MunkiImporter
MunkiImporter: Copied pkginfo to /Users/Shared/munki_repo/pkgsinfo/Applications/Adobe/AdobeXD2020/AdobeXD2020-27.0.12.6.plist
MunkiImporter: Copied pkg to /Users/Shared/munki_repo/pkgs/Applications/Adobe/AdobeXD2020/AdobeXD2020_Install-27.0.12.6.dmg
Receipt written to /Users/vagrant/Library/AutoPkg/Cache/local.munki.AdobeXD2020/receipts/local.munki-receipt-20200213-162339.plist

The following new items were imported into Munki:
    Name         Version    Catalogs  Pkginfo Path                                                Pkg Repo Path                                                     
    ----         -------    --------  ------------                                                -------------                                                     
    AdobeXD2020  27.0.12.6  testing   Applications/Adobe/AdobeXD2020/AdobeXD2020-27.0.12.6.plist  Applications/Adobe/AdobeXD2020/AdobeXD2020_Install-27.0.12.6.dmg  

Report plist saved to /Users/vagrant/Downloads/adobe2020_report.plist.
```

**AutoPkg 1.4.1 + Adobe2020Importer.py imports into Munki repo successfully**

Next test will be a test with same approach but using AutoPkg 2.0.x for comparison.

**Comment by jps3** [comment]
- Testing VM with macOS 10.14.6
- AutoPkg 2.0.2
- Munki 4.0.1.3914

###  Munki 4 + AutoPkg 2.0.2 Setup
```
$ cd ~/Downloads

$ wget -q https://github.com/munki/munki/releases/download/v4.1.0/munkitools-4.1.0.3914.pkg
$ sudo installer -target / -pkg munkitools-4.1.0.3914.pkg
Password:
installer: Package name is Munki - Managed software installation for macOS
installer: Installing at base path /
installer: The install was successful.
installer: The install requires restarting now.

$ exec $SHELL --login  # reload shell to update env (for PATH)
$ mkdir -p /Users/Shared/munki_repo
$ munkiimport --configure
Repo URL (example: afp://munki.example.com/repo): file:///Users/Shared/munki_repo
pkginfo extension (Example: .plist): .plist
pkginfo editor (examples: /usr/bin/vi or TextMate.app; leave empty to not open an editor after import): /usr/bin/vi
Default catalog to use (example: testing): testing
Repo access plugin (defaults to FileRepo): 

$ wget -q https://github.com/autopkg/autopkg/releases/download/v2.0.2/autopkg-2.0.2.pkg
$ sudo installer -target / -pkg autopkg-2.0.2.pkg
Password:
installer: Package name is autopkg-2.0.2
installer: Installing at base path /
installer: The install was successful.

$ defaults write com.github.autopkg MUNKI_REPO -string '/Users/Shared/munki_repo'

$ autopkg repo-add dataJAR-recipes
Attempting git clone...

Adding /Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
  '.'
  '~/Library/AutoPkg/Recipes'
  '/Library/AutoPkg/Recipes'
  '/Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes'
```

### Prepare AdobeXD2020 Package for Import Test
```
$ autopkg make-override -n AdobeXD2020.munki "com.github.dataJAR-recipes.munki.Import Adobe 2020 Title"
Override file saved to /Users/vagrant/Library/AutoPkg/RecipeOverrides/AdobeXD2020.munki.recipe

$ sed -i '' -e 's/SomeAdobe2020Title/AdobeXD2020/' /Users/vagrant/Library/AutoPkg/RecipeOverrides/AdobeXD2020.munki.recipe

$ ditto -xkv /Volumes/VMware\ Shared\ Folders/AdobeCC_SharedDeviceLicenses/AdobeXD2020_en_US_MAC.zip .
Copying /Volumes/VMware Shared Folders/AdobeCC_SharedDeviceLicenses/AdobeXD2020_en_US_MAC.zip 

$ ditto -xk /Volumes/VMware\ Shared\ Folders/AdobeCC_SharedDeviceLicenses/AdobeXD2020_en_US_MAC.zip .
$ ls -F
AdobeXD2020/
```

### Adobe2020Importer.py Test
```
$ ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe\ 2020/Adobe2020Importer.py munki 
.1 Adobe 2020 folder found, creating recipe list...
Looking for pkgs...
Found /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg...
Running recipe_list: `/Users/vagrant/Downloads/adobe2020_list.txt`

Running `['/usr/local/bin/autopkg', 'run', '-v', '--recipe-list', '/Users/vagrant/Downloads/adobe2020_list.txt', '--report-plist', '/Users/vagrant/Downloads/adobe2020_report.plist']`...
Processing local.munki.AdobeXD2020...
WARNING: /Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py: No module named 'FoundationPlist'
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 891, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py", line 49, in <module>
    import FoundationPlist
ModuleNotFoundError: No module named 'FoundationPlist'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 891, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
Failed.
Receipt written to /tmp/receipts/local.munki-receipt-20200213-165243.plist

The following recipes failed:
    local.munki.AdobeXD2020
        Unable to import 'Adobe2020Versioner', likely due to syntax or Python error.

Nothing downloaded, packaged or imported.

Report plist saved to /Users/vagrant/Downloads/adobe2020_report.plist.
```

**AutoPkg 2.0.2 + Adobe2020Importer.py fails**

**Comment by jps3** [comment]
Testing a quick-and-dirty patch

Listed here to show what was change, not necessarily a patch to be used in master since it would most likely break AutoPkg 1.x.

I don't know offhand how one would go about testing for which version of AutoPkg was running and importing the correct plist library. Or, at least, certainly not an elegant or likely reliable solution.

```
diff --git a/Adobe 2020/Adobe2020Versioner.py b/Adobe 2020/Adobe2020Versioner.py
index 98e0441..d15e326 100755
--- a/Adobe 2020/Adobe2020Versioner.py  
+++ b/Adobe 2020/Adobe2020Versioner.py  
@@ -46,7 +46,7 @@ from xml.etree import ElementTree
 
 # AutoPkg Imports
 # pylint: disable=import-error
-import FoundationPlist
+import plistlib
 from autopkglib import Processor, ProcessorError
 
 # Details
@@ -260,7 +260,7 @@ class Adobe2020Versioner(Processor):
                                     try:
                                         with myzip.open(zip_bundle) as myplist:
                                             plist = myplist.read()
-                                            data = FoundationPlist.readPlistFromString(plist)
+                                            data = plistlib.readPlistFromBytes(plist)
                                             # If the App is Lightroom (Classic or non-Classic) we need to compare a different value in Info.plist
                                             if self.env['sap_code'] == 'LTRM' or self.env['sap_code'] == 'LRCC':
                                                 self.env['vers_compare_key'] = 'CFBundleVersion'
```

### Adobe2020Importer.py Test 001
```
$ ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe\ 2020/Adobe2020Importer.py munki 
1 Adobe 2020 folder found, creating recipe list...
Looking for pkgs...
Found /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg...
Running recipe_list: `/Users/vagrant/Downloads/adobe2020_list.txt`

Running `['/usr/local/bin/autopkg', 'run', '-v', '--recipe-list', '/Users/vagrant/Downloads/adobe2020_list.txt', '--report-plist', '/Users/vagrant/Downloads/adobe2020_report.plist']`...
Processing local.munki.AdobeXD2020...
Failed local trust verification.
Receipt written to /tmp/receipts/local.munki-receipt-20200213-165857.plist

The following recipes failed:
    local.munki.AdobeXD2020
        Processor Adobe2020Versioner contents differ from expected.
            Path: /Users/vagrant/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Adobe 2020/Adobe2020Versioner.py

Nothing downloaded, packaged or imported.

Report plist saved to /Users/vagrant/Downloads/adobe2020_report.plist.
```

### Adobe2020Importer.py Test 002
```
$ autopkg run --ignore-parent-trust-verification-errors -v --recipe-list adobe2020_list.txt --report-plist adobe2020_report.plist
autopkg run --ignore-parent-trust-verification-errors -v --recipe-list adobe2020_list.txt --report-plist adobe2020_report.plistProcessing local.munki.AdobeXD2020...
Adobe2020Versioner
Adobe2020Versioner: pkg /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg
Adobe2020Versioner: Processing /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/optionXML.xml
Adobe2020Versioner: SAP Code: SPRK
Adobe2020Versioner: Installer is HyperDrive
Adobe2020Versioner: app_json: /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/HD/SPRK27.0.12/Application.json
Adobe2020Versioner: Processing HD installer
Adobe2020Versioner: app_launch: [INSTALLDIR]/Adobe XD.app/Contents/MacOS/Adobe XD
Adobe2020Versioner: app_bundle: Adobe XD.app
Adobe2020Versioner: app_path: Adobe XD
Adobe2020Versioner: installed_path: /Applications/Adobe XD/Adobe XD.app
Adobe2020Versioner: display_name: Adobe XD 2020
Adobe2020Versioner: zip_file: coreAssets
Adobe2020Versioner: zip_path: /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg/Contents/Resources/HD/SPRK27.0.12/coreAssets.zip
Adobe2020Versioner: bundle_location: [StagingFolder]/mul
Adobe2020Versioner: vers_compare_key: CFBundleShortVersionString
Adobe2020Versioner: staging_folder: mul
Adobe2020Versioner: staging_folder_path: 1/mul/Adobe XD.app/Contents/Info.plist
Adobe2020Versioner: app_version: 27.0.12.6
Adobe2020Versioner: app_bundle: Adobe XD.app
Adobe2020Versioner: additional_pkginfo: {'display_name': 'Adobe XD 2020', 'minimum_os_version': '10.13.0', 'installs': [{'CFBundleShortVersionString': '27.0.12.6', 'path': '/Applications/Adobe XD/Adobe XD.app', 'type': 'application', 'version_comparison_key': 'CFBundleShortVersionString'}]}
DmgCreator
DmgCreator: Created dmg from /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Install.pkg at /Users/vagrant/Library/AutoPkg/Cache/local.munki.AdobeXD2020/AdobeXD2020_Install-27.0.12.6.dmg
DmgCreator
DmgCreator: Created dmg from /Users/vagrant/Downloads/AdobeXD2020/Build/AdobeXD2020_Uninstall.pkg at /Users/vagrant/Library/AutoPkg/Cache/local.munki.AdobeXD2020/AdobeXD2020_Uninstall-27.0.12.6.dmg
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'display_name': 'Adobe XD 2020', 'minimum_os_version': '10.13.0', 'installs': [{'CFBundleShortVersionString': '27.0.12.6', 'path': '/Applications/Adobe XD/Adobe XD.app', 'type': 'application', 'version_comparison_key': 'CFBundleShortVersionString'}]} into pkginfo
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'version': '27.0.12.6'} into pkginfo
MunkiImporter
MunkiImporter: Copied pkginfo to /Users/Shared/munki_repo/pkgsinfo/Applications/Adobe/AdobeXD2020/AdobeXD2020-27.0.12.6.plist
MunkiImporter: Copied pkg to /Users/Shared/munki_repo/pkgs/Applications/Adobe/AdobeXD2020/AdobeXD2020_Install-27.0.12.6.dmg
Receipt written to /Users/vagrant/Library/AutoPkg/Cache/local.munki.AdobeXD2020/receipts/local.munki-receipt-20200213-170321.plist

The following new items were imported into Munki:
    Name         Version    Catalogs  Pkginfo Path                                                Pkg Repo Path                                                     
    ----         -------    --------  ------------                                                -------------                                                     
    AdobeXD2020  27.0.12.6  testing   Applications/Adobe/AdobeXD2020/AdobeXD2020-27.0.12.6.plist  Applications/Adobe/AdobeXD2020/AdobeXD2020_Install-27.0.12.6.dmg  

Report plist saved to adobe2020_report.plist.
```

**AutoPkg 2.0.2 + _patched_ Adobe2020Importer.py successfully imports into munki**

**Comment by jps3** [comment]
That's enough for this afternoon, I am going to get a friggin' 🍺. Cheers.

**Comment by macmule** [comment]
@jps3 so, you need python 3 versions of the processors for autopkg2 , right?

**Comment by jps3** [comment]
I am not sure, and I should be careful before making any pronouncements.

Is the defining difference between an AutoPkg2 Processor vs an AutoPkg3 Processor the use of `FoundationPlist[.readPlistFromString()]` (for python2) vs `plistlib[.readPlistFromBytes()]` (for python3)?

**Comment by macmule** [comment]
@jps3 I updated the recipes last night & the autopkg wiki.. try again please!

**Comment by jps3** [comment]
First test (AdobeBridge2020) on macOS 10.14.6 18G3020 with AutoPkg 2.0.2 and Munki 4.0.1.3899 was successful.

About to run it again but on all remaining app packages from last week's updates.

**Comment by jps3** [comment]
Success! Your recent patches seem to have worked flawlessly. Thank you so much.

![Screen Shot 2020-02-17 at 1 16 48 PM](https://user-images.githubusercontent.com/379162/74678048-de494500-5187-11ea-8853-b8156667ee22.png)

**Comment by macmule** [comment]
Awesome, closing this one off.
