### ISSUE TITLE
VMwareFusion10URLProvider Error

### ISSUE THREAD

**Issue by apizz** [autopkg/dataJAR-recipes#91]
autopkg version: 2.1
macOS version: 10.14.6

Verbose recipe output:

```
autopkg run VMwareFusion10.or.munki -vv
Processing local.munki.or.VMwareFusion10...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2887, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2881, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2397, in run_recipes
    autopackager.verify(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 599, in verify
    step["Processor"], verbose=self.verbose, recipe=recipe, env=self.env
  File "/Library/AutoPkg/autopkglib/__init__.py", line 894, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/VMware Fusion 10/VMwareFusion10URLProvider.py", line 68
    except URLError, e:
                   ^
SyntaxError: invalid syntax
```

**Comment by macmule** [comment]
Yea, that's not been update for autopkg2

can you test swapping out the VMwareFusion10URLProvider section  for something like:

>         <dict>
>             <key>Processor</key>
>             <string>com.justinrummel.download.VMwareFusion/VMwareFusionURLProvider</string>
>             <key>Arguments</key>
>             <dict>
>                 <key>major_version</key>
>                 <string>10</string>
>                 <key>product_name</key>
>                 <string>fusion.xml</string>
>             </dict>
>         </dict>

**Comment by apizz** [comment]
Yep that works.  Although, since the software hasn't been updated since 2019, it has a deprecation warning.  Guess I should remove the override then ...

**Comment by macmule** [comment]
yea, we'll tidy up here too... thanks for the heads up

**Comment by macmule** [comment]
We actually already have the deprecation in the downloads.
